# -*- coding: utf-8 -*-
"""Project Telco - Random Forest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gtBwrZsOVqd1hdUTBrwXR7uO0Tq_CrlW
"""

import pandas as pd
import io

from google.colab import files
data_to_load = files.upload()
    
df = pd.read_csv(io.BytesIO(data_to_load['dqlab_telco_encoded.csv']), error_bad_lines=False)

#define variable data by removing the variable target
data = df[["tenure", "MonthlyCharges", "PaperlessBillingcode"]]
data.head()

#define variable target
target = df["Churncode"]
target.head()

# Import train_test_split function
from sklearn.model_selection import train_test_split

# Split dataset into training set and test set
xtrain, xtest, ytrain, ytest = train_test_split(data, target, test_size=0.20,random_state=123) # 80% training and 20% test

#Feature scaling to scale the data or commonly known as normalization
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(xtrain)
xtrain = scaler.transform(xtrain)
xtest = scaler.transform(xtest)

#Implementing Random Forest Algorithm
from sklearn import metrics
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators = 300, criterion="entropy")
rf.fit(xtrain, ytrain)
y_pred_RF = rf.predict(xtest)

# Making Confusion Matrix
from sklearn.metrics import classification_report, confusion_matrix
confusion_matrix(ytest, y_pred_RF)

#Calculating Precision, Recall, F1-score, and Accuracy
print(classification_report(ytest, y_pred_RF))

