# -*- coding: utf-8 -*-
"""Project Telco - Naive Bayes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m7Mx3daaBMx2_MgHIYxqFMoPOgXTU7xR
"""

import pandas as pd
import io

from google.colab import files
data_to_load = files.upload()
    
df = pd.read_csv(io.BytesIO(data_to_load['dqlab_telco_encoded.csv']), error_bad_lines=False)

#define variable data by removing the target variable
data = df[["tenure", "MonthlyCharges", "PaperlessBillingcode"]]
data.head()

#define variable target
target = df["Churncode"]
target.head()

# Import train_test_split function
from sklearn.model_selection import train_test_split

# Split dataset into training set and test set
xtrain, xtest, ytrain, ytest = train_test_split(data, target, test_size=0.20,random_state=123) # 80% training and 20% test

#Feature scaling to scale the data or commonly known as normalization
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(xtrain)
xtrain = scaler.transform(xtrain)
xtest = scaler.transform(xtest)

#Implementing Naive Bayes Algorithm
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB

nb = GaussianNB()
nb.fit(xtrain, ytrain)
y_pred_NB = nb.predict(xtest)

# Membuat Confusion Matrix
confusion_matrix(ytest, y_pred_NB)

#Calculating Precision, Recall, F1-score, and Accuracy
print(classification_report(ytest, y_pred_NB))

