# -*- coding: utf-8 -*-
"""Project Telco - KNN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13uCQ4E6uvvvDpPY4juRkMigcKFJbbd_o
"""

import pandas as pd
import io

from google.colab import files
data_to_load = files.upload()
    
df = pd.read_csv(io.BytesIO(data_to_load['dqlab_telco_encoded.csv']), error_bad_lines=False)

#define variable data by removing the variable target
x = df[["tenure", "MonthlyCharges", "PaperlessBillingcode"]]
x.head()

#define variable target
y = df["Churncode"]
y.head()

# Import train_test_split function
from sklearn.model_selection import train_test_split

# Split dataset into training set and test set
xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=0.20)

#Implementing K-Nearest Neighbors Algorithm

import numpy as np  

# Activate StandardScaler package from SKlearn and write syntax to scale data
from sklearn.neighbors import KNeighborsClassifier

# Enable the classification function for KNN
knn = KNeighborsClassifier (n_neighbors=5)

# Enter training data in the classification function for KNN
knn.fit(xtrain,ytrain)

#Determine predictions or forecasts
ypred = knn.predict(xtest)
ypred= pd.DataFrame(ypred)

#Import package to see the accuracy of the predicted data with the actual data
from sklearn.metrics import classification_report, confusion_matrix

# Displays the prediction result matrix
print(confusion_matrix(ytest,ypred))

#measure the accuracy or accuracy of the prediction results
print(classification_report(ytest,ypred))

