# -*- coding: utf-8 -*-
"""Project Telco - Decision Tree.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1arb06CtzuWR9YLaXdluMznLkaYJ2R2qH
"""

import pandas as pd
import io

from google.colab import files
data_to_load = files.upload()
    
df = pd.read_csv(io.BytesIO(data_to_load['dqlab_telco_encoded.csv']), error_bad_lines=False)

df["Churncode"].value_counts()

#define variable data by removing the target variable
data = df[["tenure", "MonthlyCharges", "PaperlessBillingcode"]]
data.head()

#define variable target
target = df["Churncode"]
target.head()

# Import train_test_split function
from sklearn.model_selection import train_test_split

# Split dataset into training set and testing set
xtrain, xtest, ytrain, ytest = train_test_split(data, target, test_size=0.20,random_state=123) # 80% training and 20% test

#Feature scaling to scale the data or commonly known as normalization
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(xtrain)
xtrain = scaler.transform(xtrain)
xtest = scaler.transform(xtest)

#Implementing Decision Tree Algorithm
from sklearn import metrics
from sklearn.tree import DecisionTreeClassifier 
from sklearn import tree 

dt = tree.DecisionTreeClassifier(criterion="entropy")
dt.fit(xtrain, ytrain)
ypred = dt.predict(xtest)

# Making Confusion Matrix
from sklearn.metrics import classification_report, confusion_matrix
confusion_matrix(ytest, ypred)

#Calculating Precision, Recall, F1-score, and Accuracy
from sklearn.metrics import classification_report
print(classification_report(ytest, ypred))

