# -*- coding: utf-8 -*-
"""Project Telco - SVM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MeBzEHx_Eq_-L8lNhmddWQN3imD2X5eb
"""

import pandas as pd
import io

from google.colab import files
data_to_load = files.upload()
    
df = pd.read_csv(io.BytesIO(data_to_load['dqlab_telco_encoded.csv']), error_bad_lines=False)

#define variable data by removing the target variable
data = df[["tenure", "MonthlyCharges", "PaperlessBillingcode"]]
data.head()

#define variable target
target = df["Churncode"]
target.head()

# Import train_test_split function
from sklearn.model_selection import train_test_split

# Split dataset into training set and test set
xtrain, xtest, ytrain, ytest = train_test_split(data, target, test_size=0.20,random_state=123) # 80% training and 20% test

#Implementing Support Vector Machine Algorithm

#Train the model using the training sets
from sklearn.svm import LinearSVC
clf = LinearSVC(random_state=0, tol=1e-5)
clf.fit(xtrain, ytrain.ravel()) 

#Predict the response for test dataset
ypred = clf.predict(xtest)
ytest = ytest.to_numpy()

# Making Confusion Matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(ytest, ypred)

#Calculating Precision, Recall, F1-score, and Accuracy
from sklearn.metrics import classification_report
print(classification_report(ytest, ypred))

